/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "surface-container-high": "#2a2a2a",
        "on-background": "#e5e2e1",
        "on-secondary-fixed-variant": "#474747",
        "inverse-primary": "#005bc0",
        "on-surface-variant": "#c1c6d7",
        "on-tertiary-container": "#292a2a",
        "on-secondary": "#303030",
        "on-primary": "#002e68",
        "on-secondary-container": "#b6b5b4",
        "tertiary-fixed-dim": "#c7c6c6",
        "surface-container": "#20201f",
        "surface-bright": "#393939",
        "inverse-surface": "#e5e2e1",
        "secondary": "#c8c6c6",
        "on-tertiary-fixed": "#1b1c1c",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353535",
        "secondary-container": "#474747",
        "surface-container-lowest": "#0e0e0e",
        "background": "#131313",
        "secondary-fixed": "#e4e2e1",
        "primary": "#adc7ff",
        "on-tertiary": "#303031",
        "outline-variant": "#414754",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed-dim": "#c8c6c6",
        "primary-fixed": "#d8e2ff",
        "surface-dim": "#131313",
        "primary-container": "#4a8eff",
        "surface-container-low": "#1b1b1b",
        "primary-fixed-dim": "#adc7ff",
        "error-container": "#93000a",
        "tertiary": "#c7c6c6",
        "error": "#ffb4ab",
        "on-surface": "#e5e2e1",
        "tertiary-fixed": "#e3e2e2",
        "on-primary-container": "#00285b",
        "surface-tint": "#adc7ff",
        "inverse-on-surface": "#313030",
        "tertiary-container": "#919090",
        "outline": "#8b90a0",
        "on-error": "#690005",
        "surface-variant": "#353535",
        "on-primary-fixed": "#001a41",
        "on-tertiary-fixed-variant": "#464747",
        "on-secondary-fixed": "#1b1c1c"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
